### ISSUE TITLE
Issues with running the code and some suggestions. 

### ISSUE THREAD

**Issue by aswinkumar1999** [murale127/viewgrades-scraper#1]
#### Issue : 

Followed the setup guide and faced this problem : 

```bash
$ python3 PageLogin.py
Enter your roll number:ep18b014
Enter your password:
Traceback (most recent call last):
  File "PageLogin.py", line 42, in <module>
    name = driver.find_element_by_xpath("/html/body/center/table/tbody/tr/th[3]")
  File "/home/aswinkumar99/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "/home/aswinkumar99/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/aswinkumar99/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/aswinkumar99/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: /html/body/center/table/tbody/tr/th[3]
```

If I am not wrong, after authentication, the page redirects me to : 

```
https://www.iitm.ac.in/viewgrades/studentauth/studpass.php
```

but the link in your code is different and it throws a "Cannot connect to SQL Server Error" in the Firefox browser. Also because this is empty you get an "Unable to locate element" message above.

https://github.com/murale127/viewgrades-scraper/blob/a23a184647e6ce241a2a6f4de2e4abc4e1ac1e2c/PageLogin.py#L37-L38

#### Suggestion  : 

We can invoke the Firefox browser headless using this 

```
from selenium.webdriver.firefox.options import Options

options = Options()
options.headless = True
driver = webdriver.Firefox(options=options, executable_path=r"./geckodriver-v0.26.0-linux64/geckodriver")
```

https://github.com/murale127/viewgrades-scraper/blob/a23a184647e6ce241a2a6f4de2e4abc4e1ac1e2c/PageLogin.py#L8

**Comment by murale127** [comment]
@aswinkumar1999 Thanks for the suggestion!
Following changes have been made:

1. Invoking Firefox browser headless
2. And added a .gitignore file for .log and .pyc files.

Regarding your issue about "Cannot connect to SQL Server Error", Viewgrades throws this error sometimes when someone tries to login.

The webpage after authentication
`https://www.iitm.ac.in/viewgrades/studentauth/studpass.php`
renders(not sure if this the right word) in it.
`https://www.iitm.ac.in/viewgrades/studentauth/btechdual.php`
This page removes the name of the institute and the logo on top and only the table is rendered.

Will add a check for this case, had missed it. Thanks for bringing it to my notice.

**Comment by aswinkumar1999** [comment]
Closing issue as it is resolved.
